### ISSUE TITLE
Net 9 Rendering Problem

### ISSUE THREAD

**Issue by Manmohabe** [ardalis/SmartEnum#558]
I am still encountering the errors mentioned in #556. The suggested fix does not work on my end, as I am using the latest version, 8.2.

```
Could not set up parent class, due to: Recursive type definition detected Ardalis.SmartEnum.SmartEnum`2 assembly:Ardalis.SmartEnum.dll type:SmartEnum`2 member:(null)

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Field not found: Module.Shared.Common.Enums.Section Module.Shared.Common.Enums.Section.BankingAccount Due to: Could not find field in class
System.MissingFieldException: Field not found: Module.Shared.Common.Enums.Section Module.Shared.Common.Enums.Section.BankingAccount Due to: Could not find field in class
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Radzen.Blazor.RadzenFormField.<BuildRenderTree>b__38_1(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Microsoft.AspNetCore.Components.CascadingValue`1[[Radzen.Blazor.IFormFieldContext, Radzen.Blazor, Version=5.6.2.0, Culture=neutral, PublicKeyToken=null]].Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by Manmohabe** [comment]
After deleting the bin folder and doing a fresh build, i haven't encountered the above problem. Closing this for now.

**Comment by JohnMarsing** [comment]
deleting the bid folder and rebuilding worked for me well 😁
Thanks @Manmohabe
